name: Deploy Limone App

#on:
#  push:
#    paths:
#    - limone-api/Application/**
      
env:
   DEFAULT_LOCATION: uksouth
   LIMONE_ALIAS: zlimone
   ZODIAC_ALIAS: zzodiac

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{env.ZODIAC_ALIAS}}acr.azurecr.io
        username: ${{env.ZODIAC_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        docker build -f limone-api/Application/Dockerfile -t ${{env.ZODIAC_ALIAS}}acr.azurecr.io/zodiac/limone-api:${{github.run_number}} .
        docker push ${{env.ZODIAC_ALIAS}}acr.azurecr.io/zodiac/limone-api:${{github.run_number}}
    - name: 'Set Function App Docker Image'
      shell: bash
      run: |
        az webapp config container set --docker-custom-image-name ${{env.ZODIAC_ALIAS}}acr.azurecr.io/zodiac/limone-api:${{github.run_number}} \
             --docker-registry-server-password ${{ secrets.ACR_PASSWORD }} \
             --docker-registry-server-url https://${{env.ZODIAC_ALIAS}}acr.azurecr.io \
             --docker-registry-server-user ${{env.ZODIAC_ALIAS}}acr \
             --name ${{env.LIMONE_ALIAS}}-api \
             --resource-group ${{env.LIMONE_ALIAS}}-rg
        az webapp log config --docker-container-logging filesystem \
             --name ${{env.LIMONE_ALIAS}}-api \
             --resource-group ${{env.LIMONE_ALIAS}}-rg
    
    - name: Azure logout
      run: |
        az logout
