name: Deploy Zodiac App
env:
   DEFAULT_LOCATION: northeurope
   ZODIAC_ALIAS: zaxzodiac

#on:
#  push:
#    paths:
#    - Zodiac.Generator/**

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{env.ZODIAC_ALIAS}}acr.azurecr.io
        username: ${{env.ZODIAC_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        docker build -f Zodiac.Generator/Dockerfile -t ${{env.ZODIAC_ALIAS}}acr.azurecr.io/zodiac/generator:${{github.run_number}} .
        docker push ${{env.ZODIAC_ALIAS}}acr.azurecr.io/zodiac/generator:${{github.run_number}}


    - name: 'Set Function App Docker Image'
      shell: bash
      run: |
        az functionapp config container set --docker-custom-image-name ${{env.ZODIAC_ALIAS}}acr.azurecr.io/zodiac/generator:${{github.run_number}} \
             --docker-registry-server-password ${{ secrets.ACR_PASSWORD }} \
             --docker-registry-server-url https://${{env.ZODIAC_ALIAS}}acr.azurecr.io \
             --docker-registry-server-user ${{env.ZODIAC_ALIAS}}acr \
             --name ${{env.ZODIAC_ALIAS}}-gen-func \
             --resource-group ${{env.ZODIAC_ALIAS}}-rg
        az webapp log config --docker-container-logging filesystem \
             --name ${{env.ZODIAC_ALIAS}}-gen-func \
             --resource-group ${{env.ZODIAC_ALIAS}}-rg
    
    - name: Azure logout
      run: |
        az logout


