name: Deploy Scorpio App
env:
  DEFAULT_LOCATION: uksouth
  SCORPIO_ALIAS: bpscorpio
#on:
#  push:
#    paths:
#    - scorpio-api/Application/**

on: [workflow_dispatch]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
                
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Build Application
      run: dotnet build scorpio-api/Application/scorpio-api.csproj --configuration Debug

    - name: Publish Application
      run: |
        dotnet publish scorpio-api/Application/scorpio-api.csproj -c Debug -o ${{env.DOTNET_ROOT}}/myapp 
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: 'Deploy Web Application'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{env.SCORPIO_ALIAS}}-api
        package: ${{env.DOTNET_ROOT}}/myapp 


        
