name: Deploy All Infrastructure
env:
   DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}

on: [workflow_dispatch]
 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
                    
      - name: Setup .NET Core 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
   
      - name: Run Deployment Scripts
        run: |
                chmod +x deployment_scripts/set_environment.sh
                chmod +x deployment_scripts/deploy_infrastructure.sh
                chmod +x deployment_scripts/deploy_sirmione_web.sh
                chmod +x deployment_scripts/deploy_scorpio_api.sh
                chmod +x deployment_scripts/deploy_limone_api.sh
                chmod +x deployment_scripts/deploy_virgo.sh
                chmod +x deployment_scripts/deploy_libra.sh
                chmod +x deployment_scripts/deploy_zodiac_generator.sh
                deployment_scripts/deploy_infrastructure.sh
