# This workflow will deploy the front end component of the application.
# To get this workflow to trigger you need to edit one of the files in the Sirmione-Web project.
# to change the name of the resource edit the ALIAS below

on:
  push:
    paths:
    - sirmione-web/Application/Sirmione.Web/**

name: Sirmione-Web
env:
  DEFAULT_LOCATION: westeurope
  SIRMIONE_ALIAS: asirmione

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Environment Variables
      run: |
             echo $SIRMIONE_ALIAS
             echo $DEFAULT_LOCATION
             
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1.101
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Build Application
      run: dotnet build sirmione-web/Application/Sirmione.Web/Sirmione.Web.csproj --configuration Release

    - name: Publish Application
      run: |
        dotnet publish sirmione-web/Application/Sirmione.Web/Sirmione.Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp 
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - name: 'Deploy Web Application'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{env.SIRMIONE_ALIAS}}-web
        package: ${{env.DOTNET_ROOT}}/myapp 
       
    
